apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-pv-uuidgen
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /cephfs/jupyterhubpv/uuidgen
